dataset:
  name: "ICFHR2022_train"
  shuffle: true

dataset_test:
  name: "ICFHR2022_test"
  shuffle: false

training:
  learning_rate: 1e-4
  epochs: 200
  decay_epochs: 50
  decay_factor: 0.5
  optimizer: ADAM
  # optimizer: SGD
  batch_size: 4

model:
  initialization: null
  name: model.pth
  # Fixed: letters of greek alphabet
  torch_module:
    _target_: torchvision.models.detection.retinanet_resnet50_fpn_v2
    kwargs:
      pretrained: true
      num_classes: 26
